# Generated by Django 4.2.26 on 2025-11-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='en_prestamo',
            field=models.BooleanField(default=False),
        ),
    ]
