# Generated by Django 4.2.26 on 2025-11-30 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libros', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(null=True)),
                ('fecha_devolucion', models.DateTimeField(null=True)),
                ('libro_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='libros.libro')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='usuarios.usuario')),
            ],
            options={
                'verbose_name_plural': 'Prestamos',
            },
        ),
    ]
