# Generated by Django 4.2.26 on 2025-11-30 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='libro_id',
            new_name='libro',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
