# Generated by Django 4.2.26 on 2025-11-30 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_libro_en_prestamo'),
        ('usuarios', '0001_initial'),
        ('prestamos', '0002_rename_libro_id_prestamo_libro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='prestamos', to='libros.libro'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='prestamos', to='usuarios.usuario'),
        ),
    ]
